/**
 * Config plugin: release builds drop the INTERNET permission entirely, so the
 * shipped game provably cannot talk to the network. Debug builds keep it
 * (Metro / dev tools need it).
 */
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

const RELEASE_MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withOfflineRelease.js -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
    <uses-permission android:name="android.permission.INTERNET" tools:node="remove" />
</manifest>
`;

module.exports = function withOfflineRelease(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'release');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'AndroidManifest.xml'), RELEASE_MANIFEST);
      return cfg;
    },
  ]);
};
