/**
 * English strings — the source of truth. Keys are flat and grouped by screen.
 * `{name}` placeholders are interpolated; keys ending in `_one`/`_other` are
 * chosen by the `count` param.
 */
export const en = {
  'app.name': 'Imposter Party',
  'app.tagline': 'One phone. One secret. One liar.',

  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.continue': 'Continue',
  'common.delete': 'Delete',
  'common.done': 'Done',
  'common.next': 'Next',
  'common.save': 'Save',
  'common.reset': 'Reset',
  'common.skip': 'Skip',
  'common.on': 'On',
  'common.off': 'Off',
  'common.seconds': '{count}s',
  'common.unlimited': 'No limit',
  'common.minutes': '{count} min',
  'common.points_one': '{count} pt',
  'common.points_other': '{count} pts',
  'common.players_one': '{count} player',
  'common.players_other': '{count} players',
  'common.imposters_one': '{count} Imposter',
  'common.imposters_other': '{count} Imposters',
  'common.undercovers_one': '{count} Undercover',
  'common.undercovers_other': '{count} Undercovers',
  'common.error.title': 'Oops!',
  'common.error.storage': "Couldn't save to this phone. Your game still works — try freeing up some space.",
  'common.error.generic': 'Something went wrong. Your game is safe — please try again.',

  'home.play': 'PLAY',
  'home.playHint': 'Set up players & rules',
  'home.quickPlay': 'Quick Play',
  'home.quickPlayHint': '5 players · Classic · Random words',
  'home.rules': 'Rules',
  'home.categories': 'Categories',
  'home.stats': 'Stats',
  'home.settings': 'Settings',
  'home.resumeTitle': 'Game in progress',
  'home.resumeBody': 'Round {round} · {players}',
  'home.resume': 'Resume',
  'home.abandon': 'Abandon',
  'home.wordCount': '{count}+ words · {categories} categories · 100% offline',

  'resume.title': 'Resume game?',
  'resume.body': 'You have an unfinished game with {players}. Pick up where you left off?',
  'resume.resume': 'Resume',
  'resume.new': 'Start new game',
  'resume.abandon': 'Abandon game',
  'resume.corrupted': "Your last game couldn't be restored, so we cleared it. Everything else is safe.",

  'onboarding.1.title': 'Everyone gets a secret',
  'onboarding.1.body': 'Pass one phone around. Each player privately sees the same secret word.',
  'onboarding.2.title': 'Except the Imposter',
  'onboarding.2.body': "One player gets nothing. They don't know the word — and they have to fake it.",
  'onboarding.3.title': 'Give sneaky clues',
  'onboarding.3.body':
    "Say one clue about the word. Too obvious and the Imposter catches on. Too vague and you'll look guilty!",
  'onboarding.4.title': 'Find the Imposter!',
  'onboarding.4.body': 'Discuss, vote, and unmask the liar. If they’re caught, they get one last guess at the word.',
  'onboarding.start': "Let's play",

  'players.title': "Who's playing?",
  'players.subtitle': '{players} · up to {imposters}',
  'players.addPlaceholder': 'Add a name…',
  'players.add': 'Add',
  'players.quickAdd': 'Quick add',
  'players.shuffle': 'Shuffle',
  'players.clear': 'Clear all',
  'players.clearConfirm': 'Remove all players?',
  'players.moveUp': 'Move {name} up',
  'players.moveDown': 'Move {name} down',
  'players.remove': 'Remove {name}',
  'players.rename': 'Name of player {index}',
  'players.defaultName': 'Player {index}',
  'players.empty': 'Add at least 3 players in clockwise seating order — the order you pass the phone.',
  'players.next': 'Next: Game settings',
  'players.error.tooFew': 'Add at least {min} players',
  'players.error.tooMany': 'Max {max} players',
  'players.error.blank': 'Every player needs a name',
  'players.error.duplicate': 'Two players have the same name',
  'players.error.duplicateShort': 'Name taken',
  'players.error.tooLong': 'Names can be up to {max} characters',
  'players.full': 'That’s the max — {max} players!',

  'config.title': 'Game settings',
  'config.playStyleNote': 'Playing: {style} · change in Settings',
  'config.summary': '{players} · {imposters}',
  'config.mode': 'Game mode',
  'config.imposters': 'Imposters',
  'config.undercovers': 'Undercover players',
  'config.impostersHint': 'Max {max} for {players}',
  'config.category': 'Category',
  'config.difficulty': 'Difficulty',
  'config.timers': 'Timers',
  'config.clueTimer': 'Time per clue',
  'config.discussionTimer': 'Discussion time',
  'config.roles': 'Special roles',
  'config.rolesHint': 'Optional twists. Leave off for a classic game.',
  'config.jesterNeeds': 'Needs {min}+ players',
  'config.advanced': 'More rules',
  'config.tieRule': 'If the vote is tied',
  'config.tie.revote': 'Revote',
  'config.tie.random': 'Random pick',
  'config.finalGuess': 'Imposter gets a final guess',
  'config.guessStyle': 'Final guess style',
  'config.guess.choice': 'Multiple choice',
  'config.guess.type': 'Type it',
  'config.teammates': 'Imposters know each other',
  'config.undercoverAware': 'Undercover knows their role',
  'config.chaosCount': 'Chaos twists per round',
  'config.scoring': 'Scoring',
  'config.scoringEnabled': 'Keep score',
  'config.score.civilianCorrectVote': 'Civilian votes for an Imposter',
  'config.score.civilianWin': 'Civilians win (each)',
  'config.score.imposterSurvive': 'Imposter survives',
  'config.score.imposterGuess': 'Imposter guesses the word',
  'config.score.jesterVotedOut': 'Jester gets voted out',
  'config.start': 'Deal the roles',
  'config.error.tooManyImposters': 'Too many imposters for {players}',
  'config.error.categoryEmpty': 'That category has no words yet',
  'config.error.categoryMissing': 'Pick a category',
  'config.error.needsTwoWords': 'Undercover needs a category with at least 2 words',
  'config.error.players': 'Fix the player list first',
  'config.error.noCategories': 'Random and Mixed need at least one category switched on',

  'difficulty.easy': 'Easy',
  'difficulty.medium': 'Medium',
  'difficulty.hard': 'Hard',
  'difficulty.easy.hint': 'Common, obvious words',
  'difficulty.medium.hint': 'A bit more slippery',
  'difficulty.hard.hint': 'Tough to clue without giving it away',

  'mode.classic.name': 'Classic',
  'mode.classic.desc': 'Imposter gets no word — only the category.',
  'mode.undercover.name': 'Undercover',
  'mode.undercover.desc': 'The odd one out gets a similar word. Pizza vs Burger!',
  'mode.blind.name': 'Blind',
  'mode.blind.desc': 'Imposter gets nothing. Not even the category.',
  'mode.chaos.name': 'Chaos',
  'mode.chaos.desc': 'Random twists every round. Expect anything.',

  'category.title': 'Pick a category',
  'category.random': 'Random',
  'category.random.desc': 'A surprise category each round',
  'category.mixed': 'Mixed',
  'category.mixed.desc': 'Every word from every category',
  'category.yours': 'Your categories',
  'category.builtIn': 'Built-in',
  'category.words_one': '{count} word',
  'category.words_other': '{count} words',
  'category.create': 'Create a category',
  'category.food': 'Food',
  'category.animals': 'Animals',
  'category.objects': 'Objects',
  'category.places': 'Places',
  'category.movies': 'Movies',
  'category.tv_shows': 'TV Shows',
  'category.games': 'Games',
  'category.sports': 'Sports',
  'category.technology': 'Technology',
  'category.jobs': 'Jobs',
  'category.everyday_life': 'Everyday Life',
  'category.brands': 'Brands',
  'category.celebrities': 'Celebrities',
  'category.school': 'School',
  'category.college': 'College',
  'category.travel': 'Travel',
  'category.indian_culture': 'Indian Culture',
  'category.bollywood': 'Bollywood',
  'category.cricket': 'Cricket',
  'category.indian_food': 'Indian Food',
  'category.indian_cities': 'Indian Cities',
  'category.countries': 'Countries',
  'category.internet_memes': 'Internet & Memes',
  'category.tamil_nadu': 'Tamil Nadu',
  'category.tamil_movies': 'Tamil Movies',
  'category.tamil_celebrities': 'Tamil Celebrities',
  'category.telugu_cinema': 'Telugu Cinema',
  'category.malayalam_cinema': 'Malayalam Cinema',
  'category.poolSummary': 'Random & Mixed use {on} of {total} topics',
  'category.poolEdit': 'Choose topics',

  'group.everyday': 'Everyday',
  'group.india': 'India & Tamil Nadu',
  'group.cinema': 'Movies & stars',
  'group.pop': 'Sports, games & pop culture',

  'categories.title': 'Categories',
  'categories.subtitle': 'Built-in word lists are hidden so nobody can study them 😉',
  'categories.poolTitle': 'Topics for Random & Mixed',
  'categories.poolHint':
    "Switch off topics your group doesn't know. Random and Mixed will skip them — you can still pick any category directly.",
  'categories.poolCount': '{on} of {total} topics on',
  'categories.preset.all': 'All',
  'categories.preset.everyday': 'Everyday',
  'categories.preset.tamil': 'Tamil special',
  'categories.preset.pop': 'Movies & pop',
  'categories.presets': 'Quick picks',
  'categories.customInRandom': 'Use my categories in Random & Mixed',
  'categories.toggleHint': '{words} · used by Random & Mixed',
  'categories.new': 'New category',
  'categories.emptyCustom': 'Make your own list — inside jokes, your city, your friends.',
  'categories.export': 'Export',
  'categories.import': 'Import',
  'categories.exportMessage': 'Imposter Party categories',
  'categories.importTitle': 'Import categories',
  'categories.importHint': 'Paste text exported from Imposter Party.',
  'categories.importPlaceholder': 'Paste here…',
  'categories.importPaste': 'Paste from clipboard',
  'categories.importDo': 'Import',
  'categories.importDone_one': 'Imported {count} category',
  'categories.importDone_other': 'Imported {count} categories',
  'categories.importInvalid': "That doesn't look like an Imposter Party export.",

  'editor.newTitle': 'New category',
  'editor.editTitle': 'Edit category',
  'editor.name': 'Category name',
  'editor.namePlaceholder': 'e.g. My Friends',
  'editor.emoji': 'Icon',
  'editor.words': 'Words',
  'editor.wordsCount_one': '{count} word',
  'editor.wordsCount_other': '{count} words',
  'editor.addPlaceholder': 'Add words (comma or new line separated)',
  'editor.add': 'Add',
  'editor.removeWord': 'Remove {word}',
  'editor.delete': 'Delete category',
  'editor.deleteConfirm': 'Delete "{name}"? This cannot be undone.',
  'editor.emptyName': 'Give it a name',
  'editor.emptyWords': 'Add at least one word (two for Undercover mode)',
  'editor.duplicateWords_one': '{count} duplicate skipped',
  'editor.duplicateWords_other': '{count} duplicates skipped',
  'editor.full': 'Max {max} words per category',

  'game.round': 'Round {round}',
  'game.leaveTitle': 'Leave this game?',
  'game.leaveBody': 'Scores for this game will be lost. Stats from finished rounds are kept.',
  'game.leaveConfirm': 'Leave game',
  'game.notFound': 'No game in progress',
  'game.goHome': 'Go home',
  'game.exit': 'Exit game',

  'deal.title': 'Shuffling secrets…',
  'deal.subtitle': 'Someone here is about to start lying.',

  'reveal.passTo': 'Pass the phone to',
  'reveal.progress': 'Player {current} of {total}',
  'reveal.lookAway': 'Everyone else — look away 👀',
  'reveal.ready': "I'm {name} — show me",
  'reveal.holdToReveal': 'Press & hold to reveal',
  'reveal.holdHint': 'Release to hide',
  'reveal.tapCard': 'Tap to reveal',
  'reveal.hideAndPass': 'Hide & pass the phone',
  'reveal.gotIt': 'Got it — hide & pass',
  'reveal.last': 'Hide it — everyone’s done!',
  'reveal.yourWord': 'Your word is',
  'reveal.remember': 'Remember it! Don’t say it out loud.',
  'reveal.imposterTitle': "YOU'RE THE IMPOSTER",
  'reveal.imposterBody': "You don't know the word.",
  'reveal.imposterTip': 'Listen carefully to the clues and blend in.',
  'reveal.categoryHint': 'Category: {category}',
  'reveal.teammates': 'Your partner in crime: {names}',
  'reveal.undercoverTitle': "YOU'RE UNDERCOVER",
  'reveal.undercoverBody': 'Everyone else has a different word. Blend in!',
  'reveal.innocent': '🔍 Intel: {name} is NOT on the Imposter team.',
  'reveal.suspects': '🕶️ Intel: one of {a} or {b} is hiding something.',
  'reveal.backgrounded': 'Hidden for safety. Tap when {name} is holding the phone.',

  'complete.title': "Everyone's in!",
  'complete.body': 'Put the phone where everyone can see it.',
  'complete.start': 'Start clues',
  'complete.twists': 'This round’s twists',

  'simple.title': 'Everyone has their word!',
  'simple.starts': '{name} starts',
  'simple.clockwise': 'then go clockwise',
  'simple.anticlockwise': 'then go anticlockwise',
  'simple.orderLabel': 'Speaking order',
  'simple.phoneDown': 'Phone down 📵 Give clues, discuss and vote out loud.',
  'simple.holdReveal': 'Hold to see the answer',
  'simple.holdHint': 'Only after your group has voted!',
  'simple.holding': 'Keep holding…',

  'answer.title': 'The answer',
  'answer.imposter_one': 'The Imposter was',
  'answer.imposter_other': 'The Imposters were',
  'answer.undercover_one': 'The Undercover was',
  'answer.undercover_other': 'The Undercovers were',
  'answer.compare': 'Did your group get it right? 🤔',
  'answer.nextRound': 'Next round',

  'clue.title': 'Time to give clues!',
  'clue.roundN': 'Clue round {round}',
  'clue.turn': '{name}',
  'clue.giveClue': 'Give your clue 🗣️',
  'clue.next': 'Next player',
  'clue.done': 'Clue given',
  'clue.allDone': 'All clues are in!',
  'clue.allDoneBody': 'Another lap, or time to talk?',
  'clue.anotherRound': 'Another clue round',
  'clue.startDiscussion': 'Start discussion',
  'clue.timeUp': "Time's up!",
  'clue.order': 'Clue order',
  'clue.speedRound': 'Speed round: {count}s per clue!',

  'peek.button': 'Forgot your word?',
  'peek.title': 'Who needs a peek?',
  'peek.body': 'Everyone will see who checked.',
  'peek.log': '👀 Re-checked: {names}',

  'discussion.title': 'DISCUSS',
  'discussion.subtitle': "Who's acting suspicious? 🕵️",
  'discussion.pause': 'Pause',
  'discussion.resume': 'Resume',
  'discussion.addTime': '+30s',
  'discussion.vote': 'Start voting',
  'discussion.timeUp': "Time's up! Let's vote.",
  'discussion.paused': 'Paused',
  'discussion.pausedBackground': 'Paused while the app was in the background',
  'discussion.hunt': '{hidden} still hiding · {votes} left',
  'discussion.votesLeft_one': '{count} vote',
  'discussion.votesLeft_other': '{count} votes',
  'discussion.elapsed': 'Talking for',

  'vote.title': "Who's acting suspicious? 🕵️",
  'vote.revoteTitle': 'Revote! Only the tied players.',
  'vote.progress': '{done} / {total} votes',
  'vote.passTo': 'Pass the phone to',
  'vote.ready': "I'm {name} — let me vote",
  'vote.secret': 'Votes are secret until everyone has voted.',
  'vote.chooseFor': '{name}, who is the Imposter?',
  'vote.lockIn': 'Lock in vote for {name}',
  'vote.pick': 'Pick someone',
  'vote.locked': 'Vote locked 🔒',
  'vote.lockedBody': 'Pass the phone on.',
  'vote.allIn': 'All votes are in!',
  'vote.allInBody': 'Gather round for the big reveal…',
  'vote.reveal': 'Reveal the votes',
  'vote.selected': 'Selected',

  'result.drumroll': 'The group has decided…',
  'result.votes_one': '{count} vote',
  'result.votes_other': '{count} votes',
  'result.tie': 'TIE! 🤝',
  'result.tieBody': '{names} are tied. Time for a revote.',
  'result.revote': 'Revote',
  'result.randomTie': '🎲 Tie broken at random!',
  'result.out': '{name} is voted out!',
  'result.revealRole': 'Reveal their role',

  'elim.was': '{name} was…',
  'elim.imposter': 'THE IMPOSTER! 🎭',
  'elim.undercover': 'UNDERCOVER! 🥸',
  'elim.civilian': 'INNOCENT 😇',
  'elim.detective': 'THE DETECTIVE 🔍',
  'elim.agent': 'THE SECRET AGENT 🕶️',
  'elim.jester': 'THE JESTER 🃏',
  'elim.jesterBody': "And that's exactly what they wanted.",
  'elim.civilianBody': 'Oops. Wrong person.',
  'elim.found': 'YOU FOUND THE IMPOSTER!',
  'elim.foundUndercover': 'YOU FOUND THE UNDERCOVER!',
  'elim.lastChance': 'But they get one final chance…',
  'elim.giveGuess': 'Give {name} the phone',
  'elim.stillHiding': '{hidden} still hiding · {votes} left',
  'elim.moreClues': 'Another round of clues',
  'elim.discuss': 'Straight to discussion',
  'elim.seeResults': 'See results',

  'guess.title': 'Final guess',
  'guess.passTo': 'Give the phone to',
  'guess.ready': "I'm {name} — let me guess",
  'guess.question': 'What was the secret word?',
  'guess.questionUndercover': "What was everyone else's word?",
  'guess.placeholder': 'Type your guess…',
  'guess.submit': 'Lock in guess',
  'guess.correct': 'CORRECT! 😱',
  'guess.wrong': 'WRONG! 🎉',
  'guess.theWordWas': 'The word was',
  'guess.youGuessed': '{name} guessed “{guess}”',
  'guess.accept': 'Close enough — count it',
  'guess.acceptedByGroup': 'Accepted by the group',

  'win.civilians': 'CIVILIANS WIN!',
  'win.imposters': 'IMPOSTERS WIN!',
  'win.undercovers': 'UNDERCOVER WINS!',
  'win.jester': 'THE JESTER WINS!',
  'win.reason.allCaught': 'Every imposter was caught and nobody guessed the word.',
  'win.reason.imposterSurvived': 'An imposter slipped through the vote.',
  'win.reason.imposterGuessed': 'Caught… but they guessed the word!',
  'win.reason.jesterVotedOut': 'You voted out the Jester. Classic mistake.',
  'win.reason.allCaught.undercover': 'Every undercover player was caught and nobody guessed the word.',
  'win.reason.imposterSurvived.undercover': 'An undercover player slipped through the vote.',
  'win.reason.imposterGuessed.undercover': "Caught… but they guessed everyone's word!",
  'win.secretWord': 'Secret word',
  'win.undercoverWord': 'Undercover word',
  'win.roles': 'Who was who',
  'win.scoreboard': 'Scoreboard',
  'win.eliminated': 'out',

  'role.civilian': 'Civilian',
  'role.imposter': 'Imposter',
  'role.undercover': 'Undercover',
  'role.detective': 'Detective',
  'role.jester': 'Jester',
  'role.agent': 'Secret Agent',
  'role.civilian.card': 'CIVILIAN',
  'role.detective.card': 'DETECTIVE',
  'role.agent.card': 'SECRET AGENT',
  'role.jester.card': 'JESTER',
  'role.detective.tip': 'You have intel. Use it wisely — don’t blow your cover.',
  'role.agent.tip': 'You’re on the civilians’ side, with a secret lead.',
  'role.jester.tip': 'You win if the group votes YOU out. Act suspicious!',
  'role.detective.desc': 'A civilian who learns one player who is definitely innocent.',
  'role.jester.desc': 'Knows the word, but wins only if voted out. Chaos agent.',

  'scoreboard.title': 'Scoreboard',
  'scoreboard.afterRound': 'After round {round}',
  'scoreboard.nextRound': 'Next round',
  'scoreboard.endGame': 'End game',
  'scoreboard.scoringOff': 'Scoring is off — just bragging rights.',

  'final.title': 'Game over!',
  'final.winner': '{name} takes the crown 👑',
  'final.tie': "It's a tie at the top!",
  'final.rounds_one': '{count} round played',
  'final.rounds_other': '{count} rounds played',
  'final.playAgain': 'Play again',
  'final.home': 'Home',

  'twist.shortClues': 'Clues must be 3 words or fewer.',
  'twist.firstOneWord': 'The first clue must be ONE word.',
  'twist.noRepeat': 'No repeating an idea someone already used.',
  'twist.noPhysical': 'No describing looks — no colour, shape or size.',
  'twist.lastRestriction': '{name} goes last and may only use a sound or gesture!',
  'twist.speedRound': 'Speed round! {count} seconds per clue.',
  'twist.randomOrder': 'Clue order is totally scrambled.',
  'twist.secretAgent': 'A Secret Agent is among you…',
  'twist.imposterCategory': 'The imposter knows the category this time.',
  'twist.twoWords': 'Two different words are in play. Trust no one.',

  'rules.title': 'How to play',
  'rules.styles.title': '📱 Two ways to play',
  'rules.styles.body':
    'Words only (default): pass the phone so everyone sees their word, then the phone says who starts and which way to go. Put it down, give clues, discuss and vote out loud — then hold the button to see who the Imposter really was. Full game (Settings → How you play): clues, timers, secret voting, the final guess and scores all happen on the phone.',
  'rules.basics.title': 'The basics',
  'rules.basics.body':
    'Everyone secretly gets the same word — except the Imposter, who gets nothing. Take turns giving one clue about the word. Then discuss and vote out who you think is faking it.',
  'rules.example.title': 'Example',
  'rules.example.body':
    'The word is PIZZA. Raghav says “cheesy”. Priya says “slices”. Arun (the Imposter, who only knows the category Food) says “delivery”… sounds right! Then Neha says “Italian” and Arun starts to sweat.',
  'rules.classic.title': '🎭 Classic',
  'rules.classic.body': 'The Imposter sees only the category (e.g. “Food”) and must bluff.',
  'rules.blind.title': '🙈 Blind',
  'rules.blind.body': 'The Imposter gets nothing at all — not even the category. Hard mode for liars.',
  'rules.undercover.title': '🥸 Undercover',
  'rules.undercover.body':
    'Instead of no word, the odd one out gets a similar word (Pizza vs Burger). By default they don’t even know they’re different! Their clues will feel almost right…',
  'rules.multi.title': '👥 Multiple Imposters',
  'rules.multi.body':
    'With 5+ players you can add 2 Imposters, and 3 with 7+. Civilians get one vote per Imposter and must eliminate all of them. If even one survives, the Imposters win.',
  'rules.chaos.title': '🌀 Chaos',
  'rules.chaos.body':
    'Each round adds random twists: speed rounds, one-word clues, a Secret Agent who knows one of two suspects, a second secret word, and more.',
  'rules.voting.title': '🗳️ Voting',
  'rules.voting.body':
    'Pass the phone around — everyone votes in secret, and nobody sees results until all votes are in. You can’t vote for yourself. The player with the most votes is out and their role is revealed.',
  'rules.tie.title': '🤝 Ties',
  'rules.tie.body':
    'If the top spot is tied, there’s a revote between just the tied players (or a random pick, if you chose that). If the revote is tied too, the phone picks at random.',
  'rules.guess.title': '🎯 Final guess',
  'rules.guess.body':
    'A caught Imposter gets one last chance: guess the secret word. Right? Imposters win. Wrong? Civilians win (if every Imposter is caught).',
  'rules.roles.title': '🃏 Special roles (optional)',
  'rules.roles.body':
    'Detective: a civilian who learns one player who is definitely innocent. Jester: knows the word but wins only by getting voted out — if that happens, the round ends and the Imposters win too.',
  'rules.scoring.title': '🏆 Scoring',
  'rules.scoring.body':
    'Civilians: +2 for each vote on an Imposter, +1 each when civilians win. Imposters: +3 for surviving, +5 for guessing the word. Jester: +5 for getting voted out. You can change points in game settings.',
  'rules.tips.title': '💡 Tips',
  'rules.tips.body':
    'Civilians: be specific enough to prove you know, vague enough not to give it away. Imposters: listen first, then say something safe. Everyone: suspicious silence is still suspicious.',

  'stats.title': 'Stats',
  'stats.empty': 'No games yet. Play a round and stats appear here — all real, nothing made up.',
  'stats.overview': 'All games on this phone',
  'stats.rounds': 'Rounds played',
  'stats.civilianWins': 'Civilian wins',
  'stats.imposterWins': 'Imposter wins',
  'stats.jesterWins': 'Jester wins',
  'stats.players': 'Players',
  'stats.gamesPlayed': 'Games played',
  'stats.wins': 'Wins',
  'stats.losses': 'Losses',
  'stats.winRate': 'Win rate',
  'stats.imposterGames': 'Imposter games',
  'stats.imposterWinsP': 'Imposter wins',
  'stats.civilianGames': 'Civilian games',
  'stats.timesCaught': 'Times caught',
  'stats.successfulGuesses': 'Successful word guesses',
  'stats.bestStreak': 'Best streak',
  'stats.currentStreak': 'Current streak',
  'stats.points': 'Total points',
  'stats.summaryLine': '{wins} · {rate}% win rate',
  'stats.winCount_one': '{count} win',
  'stats.winCount_other': '{count} wins',

  'settings.title': 'Settings',
  'settings.appearance': 'Appearance',
  'settings.theme': 'Theme',
  'settings.theme.dark': 'Dark',
  'settings.theme.light': 'Light',
  'settings.theme.system': 'System',
  'settings.motion': 'Animations',
  'settings.motion.system': 'System',
  'settings.motion.full': 'Full',
  'settings.motion.reduced': 'Reduced',
  'settings.language': 'Language',
  'settings.language.system': 'System',
  'settings.sound': 'Sound & feel',
  'settings.soundEffects': 'Sound effects',
  'settings.music': 'Music',
  'settings.haptics': 'Vibration',
  'settings.gameplay': 'Gameplay',
  'settings.playStyle': 'How you play',
  'settings.playStyle.simple': 'Words only',
  'settings.playStyle.full': 'Full game',
  'settings.playStyle.simpleHint':
    'The phone deals the secret words, says who starts and which way to go, then shows the answer when you’re done. Clues, discussion and voting happen out loud.',
  'settings.playStyle.fullHint':
    'Clues, timers, secret voting, the imposter’s final guess and scores all happen on the phone.',
  'settings.revealStyle': 'Secret reveal',
  'settings.reveal.tap': 'Tap',
  'settings.reveal.hold': 'Hold',
  'settings.revealHint': 'Hold = the secret shows only while your finger is down.',
  'settings.allowPeek': 'Allow “Forgot your word?”',
  'settings.keepAwake': 'Keep screen on during games',
  'settings.data': 'Your data',
  'settings.exportData': 'Export players, categories & settings',
  'settings.importData': 'Import from text',
  'settings.resetStats': 'Reset statistics',
  'settings.resetStatsTitle': 'Are you sure?',
  'settings.resetStatsBody': 'All statistics will be erased. This cannot be undone.',
  'settings.resetStatsDone': 'Statistics reset.',
  'settings.replayTutorial': 'Replay the intro',
  'settings.about': 'About',
  'settings.privacy': 'No accounts, no ads, no tracking. Everything stays on this phone.',
  'settings.version': 'Version {version}',
  'settings.importDone': 'Imported! {categories} categories, {players} players.',
  'settings.exportShare': 'Imposter Party backup',
} as const;

export type TranslationKey = keyof typeof en;
export type Dictionary = Partial<Record<TranslationKey, string>>;
