import type { Dictionary } from './en';

/** Hindi strings. Missing keys fall back to English. */
export const hi: Dictionary = {
  'app.tagline': 'एक फ़ोन। एक राज़। एक झूठा।',

  'common.back': 'वापस',
  'common.cancel': 'कैंसल',
  'common.close': 'बंद करो',
  'common.confirm': 'पक्का',
  'common.continue': 'आगे बढ़ो',
  'common.delete': 'डिलीट',
  'common.done': 'हो गया',
  'common.next': 'आगे',
  'common.save': 'सेव',
  'common.reset': 'रीसेट',
  'common.skip': 'स्किप',
  'common.on': 'ऑन',
  'common.off': 'ऑफ़',
  'common.seconds': '{count} सेकंड',
  'common.unlimited': 'कोई लिमिट नहीं',
  'common.minutes': '{count} मिनट',
  'common.points_one': '{count} पॉइंट',
  'common.points_other': '{count} पॉइंट्स',
  'common.players_one': '{count} प्लेयर',
  'common.players_other': '{count} प्लेयर्स',
  'common.imposters_one': '{count} इम्पोस्टर',
  'common.imposters_other': '{count} इम्पोस्टर्स',
  'common.undercovers_one': '{count} अंडरकवर',
  'common.undercovers_other': '{count} अंडरकवर',
  'common.error.title': 'उफ़!',
  'common.error.storage': 'इस फ़ोन में सेव नहीं हो पाया। गेम फिर भी चलेगा — थोड़ी जगह खाली करके देखो।',
  'common.error.generic': 'कुछ गड़बड़ हो गई। तुम्हारा गेम सेफ़ है — फिर से ट्राई करो।',

  'home.play': 'खेलो',
  'home.playHint': 'प्लेयर्स और रूल्स सेट करो',
  'home.quickPlay': 'क्विक प्ले',
  'home.quickPlayHint': '5 प्लेयर्स · क्लासिक · रैंडम शब्द',
  'home.rules': 'रूल्स',
  'home.categories': 'कैटेगरी',
  'home.stats': 'स्टैट्स',
  'home.settings': 'सेटिंग्स',
  'home.resumeTitle': 'गेम चल रहा है',
  'home.resumeBody': 'राउंड {round} · {players}',
  'home.resume': 'जारी रखो',
  'home.abandon': 'छोड़ दो',
  'home.wordCount': '{count}+ शब्द · {categories} कैटेगरी · 100% ऑफ़लाइन',

  'resume.title': 'गेम जारी रखें?',
  'resume.body': '{players} के साथ एक गेम अधूरा है। जहाँ छोड़ा था, वहीं से शुरू करें?',
  'resume.resume': 'जारी रखो',
  'resume.new': 'नया गेम शुरू करो',
  'resume.abandon': 'गेम छोड़ दो',
  'resume.corrupted': 'पिछला गेम वापस नहीं आ पाया, इसलिए हटा दिया। बाकी सब सेफ़ है।',

  'onboarding.1.title': 'सबको मिलता है एक राज़',
  'onboarding.1.body': 'एक ही फ़ोन घुमाओ। हर प्लेयर चुपके से एक ही सीक्रेट शब्द देखता है।',
  'onboarding.2.title': 'सिवाय इम्पोस्टर के',
  'onboarding.2.body': 'एक प्लेयर को कुछ नहीं मिलता। उसे शब्द नहीं पता — और उसे नाटक करना है।',
  'onboarding.3.title': 'चालाक क्लू दो',
  'onboarding.3.body':
    'शब्द के बारे में एक क्लू दो। ज़्यादा साफ़ बोला तो इम्पोस्टर समझ जाएगा। ज़्यादा गोल-मोल बोला तो तुम पर शक होगा!',
  'onboarding.4.title': 'इम्पोस्टर को ढूँढो!',
  'onboarding.4.body': 'बहस करो, वोट करो और झूठे को पकड़ो। पकड़ा गया तो उसे शब्द गेस करने का एक आखिरी मौका मिलेगा।',
  'onboarding.start': 'चलो खेलें',

  'players.title': 'कौन-कौन खेल रहा है?',
  'players.subtitle': '{players} · ज़्यादा से ज़्यादा {imposters}',
  'players.addPlaceholder': 'नाम लिखो…',
  'players.add': 'जोड़ो',
  'players.quickAdd': 'क्विक ऐड',
  'players.shuffle': 'शफ़ल',
  'players.clear': 'सब हटाओ',
  'players.clearConfirm': 'सारे प्लेयर्स हटा दें?',
  'players.moveUp': '{name} को ऊपर करो',
  'players.moveDown': '{name} को नीचे करो',
  'players.remove': '{name} को हटाओ',
  'players.rename': 'प्लेयर {index} का नाम',
  'players.defaultName': 'प्लेयर {index}',
  'players.next': 'आगे: गेम सेटिंग्स',
  'players.error.tooFew': 'कम से कम {min} प्लेयर्स जोड़ो',
  'players.error.tooMany': 'ज़्यादा से ज़्यादा {max} प्लेयर्स',
  'players.error.blank': 'हर प्लेयर का नाम होना चाहिए',
  'players.error.duplicate': 'दो प्लेयर्स का नाम एक जैसा है',
  'players.error.duplicateShort': 'नाम पहले से है',
  'players.error.tooLong': 'नाम ज़्यादा से ज़्यादा {max} अक्षर का हो सकता है',
  'players.full': 'बस, इतने ही — {max} प्लेयर्स!',

  'config.title': 'गेम सेटिंग्स',
  'config.summary': '{players} · {imposters}',
  'config.mode': 'गेम मोड',
  'config.imposters': 'इम्पोस्टर्स',
  'config.undercovers': 'अंडरकवर प्लेयर्स',
  'config.impostersHint': '{players} के लिए ज़्यादा से ज़्यादा {max}',
  'config.category': 'कैटेगरी',
  'config.difficulty': 'मुश्किल लेवल',
  'config.timers': 'टाइमर',
  'config.clueTimer': 'हर क्लू का टाइम',
  'config.discussionTimer': 'बहस का टाइम',
  'config.roles': 'स्पेशल रोल्स',
  'config.rolesHint': 'एक्स्ट्रा ट्विस्ट, अगर चाहो तो। क्लासिक गेम के लिए ऑफ़ रखो।',
  'config.jesterNeeds': '{min}+ प्लेयर्स चाहिए',
  'config.advanced': 'और रूल्स',
  'config.tieRule': 'अगर वोट बराबर हों',
  'config.tie.revote': 'फिर से वोट',
  'config.tie.random': 'रैंडम चुनो',
  'config.finalGuess': 'इम्पोस्टर को आखिरी गेस मिलेगा',
  'config.guessStyle': 'आखिरी गेस कैसे',
  'config.guess.choice': 'ऑप्शन में से',
  'config.guess.type': 'टाइप करके',
  'config.teammates': 'इम्पोस्टर्स एक-दूसरे को जानते हैं',
  'config.undercoverAware': 'अंडरकवर को अपना रोल पता है',
  'config.chaosCount': 'हर राउंड में कितने ट्विस्ट',
  'config.scoring': 'स्कोरिंग',
  'config.scoringEnabled': 'स्कोर रखो',
  'config.score.civilianCorrectVote': 'सिविलियन ने इम्पोस्टर को वोट दिया',
  'config.score.civilianWin': 'सिविलियन्स जीते (हर एक को)',
  'config.score.imposterSurvive': 'इम्पोस्टर बच गया',
  'config.score.imposterGuess': 'इम्पोस्टर ने शब्द गेस किया',
  'config.score.jesterVotedOut': 'जोकर वोट आउट हुआ',
  'config.start': 'रोल्स बाँटो',
  'config.error.tooManyImposters': '{players} के लिए बहुत ज़्यादा इम्पोस्टर्स',
  'config.error.categoryEmpty': 'इस कैटेगरी में अभी कोई शब्द नहीं है',
  'config.error.categoryMissing': 'एक कैटेगरी चुनो',
  'config.error.needsTwoWords': 'अंडरकवर के लिए कम से कम 2 शब्दों वाली कैटेगरी चाहिए',
  'config.error.players': 'पहले प्लेयर लिस्ट ठीक करो',

  'difficulty.easy': 'आसान',
  'difficulty.medium': 'मीडियम',
  'difficulty.hard': 'मुश्किल',
  'difficulty.easy.hint': 'आम, सीधे-सादे शब्द',
  'difficulty.medium.hint': 'थोड़े ज़्यादा फिसलन भरे',
  'difficulty.hard.hint': 'बिना पोल खोले क्लू देना मुश्किल',

  'mode.classic.name': 'क्लासिक',
  'mode.classic.desc': 'इम्पोस्टर को शब्द नहीं मिलता — सिर्फ़ कैटेगरी।',
  'mode.undercover.name': 'अंडरकवर',
  'mode.undercover.desc': 'अलग वाले को मिलता-जुलता शब्द मिलता है। पिज़्ज़ा vs बर्गर!',
  'mode.blind.name': 'ब्लाइंड',
  'mode.blind.desc': 'इम्पोस्टर को कुछ नहीं मिलता। कैटेगरी भी नहीं।',
  'mode.chaos.name': 'केऑस',
  'mode.chaos.desc': 'हर राउंड में रैंडम ट्विस्ट। कुछ भी हो सकता है।',

  'category.title': 'कैटेगरी चुनो',
  'category.random': 'रैंडम',
  'category.random.desc': 'हर राउंड में सरप्राइज़ कैटेगरी',
  'category.mixed': 'मिक्स',
  'category.mixed.desc': 'हर कैटेगरी के सारे शब्द',
  'category.yours': 'तुम्हारी कैटेगरी',
  'category.builtIn': 'बिल्ट-इन',
  'category.words_one': '{count} शब्द',
  'category.words_other': '{count} शब्द',
  'category.create': 'नई कैटेगरी बनाओ',
  'category.food': 'खाना',
  'category.animals': 'जानवर',
  'category.objects': 'चीज़ें',
  'category.places': 'जगहें',
  'category.movies': 'फ़िल्में',
  'category.tv_shows': 'टीवी शोज़',
  'category.games': 'गेम्स',
  'category.sports': 'खेल',
  'category.technology': 'टेक्नोलॉजी',
  'category.jobs': 'नौकरियाँ',
  'category.everyday_life': 'रोज़ की ज़िंदगी',
  'category.brands': 'ब्रांड्स',
  'category.celebrities': 'सेलिब्रिटीज़',
  'category.school': 'स्कूल',
  'category.college': 'कॉलेज',
  'category.travel': 'ट्रैवल',
  'category.indian_culture': 'भारतीय संस्कृति',
  'category.bollywood': 'बॉलीवुड',
  'category.cricket': 'क्रिकेट',
  'category.indian_food': 'देसी खाना',
  'category.indian_cities': 'भारतीय शहर',
  'category.countries': 'देश',
  'category.internet_memes': 'इंटरनेट और मीम्स',

  'categories.title': 'कैटेगरी',
  'categories.subtitle': 'बिल्ट-इन शब्दों की लिस्ट छुपी है ताकि कोई रट न ले 😉',
  'categories.new': 'नई कैटेगरी',
  'categories.emptyCustom': 'अपनी खुद की लिस्ट बनाओ — इनसाइड जोक्स, तुम्हारा शहर, तुम्हारे दोस्त।',
  'categories.export': 'एक्सपोर्ट',
  'categories.import': 'इम्पोर्ट',
  'categories.exportMessage': 'Imposter Party कैटेगरी',
  'categories.importTitle': 'कैटेगरी इम्पोर्ट करो',
  'categories.importHint': 'Imposter Party से एक्सपोर्ट किया हुआ टेक्स्ट पेस्ट करो।',
  'categories.importPlaceholder': 'यहाँ पेस्ट करो…',
  'categories.importPaste': 'क्लिपबोर्ड से पेस्ट करो',
  'categories.importDo': 'इम्पोर्ट',
  'categories.importDone_one': '{count} कैटेगरी इम्पोर्ट हुई',
  'categories.importDone_other': '{count} कैटेगरी इम्पोर्ट हुईं',
  'categories.importInvalid': 'ये Imposter Party का एक्सपोर्ट नहीं लग रहा।',

  'editor.newTitle': 'नई कैटेगरी',
  'editor.editTitle': 'कैटेगरी एडिट करो',
  'editor.name': 'कैटेगरी का नाम',
  'editor.namePlaceholder': 'जैसे: मेरे दोस्त',
  'editor.emoji': 'आइकन',
  'editor.words': 'शब्द',
  'editor.wordsCount_one': '{count} शब्द',
  'editor.wordsCount_other': '{count} शब्द',
  'editor.addPlaceholder': 'शब्द जोड़ो (कॉमा या नई लाइन से अलग करो)',
  'editor.add': 'जोड़ो',
  'editor.removeWord': '{word} हटाओ',
  'editor.delete': 'कैटेगरी डिलीट करो',
  'editor.deleteConfirm': '"{name}" डिलीट करें? ये वापस नहीं होगा।',
  'editor.emptyName': 'इसे एक नाम दो',
  'editor.emptyWords': 'कम से कम एक शब्द जोड़ो (अंडरकवर मोड के लिए दो)',
  'editor.duplicateWords_one': '{count} डुप्लिकेट छोड़ा गया',
  'editor.duplicateWords_other': '{count} डुप्लिकेट छोड़े गए',
  'editor.full': 'हर कैटेगरी में ज़्यादा से ज़्यादा {max} शब्द',

  'game.round': 'राउंड {round}',
  'game.leaveTitle': 'गेम छोड़ना है?',
  'game.leaveBody': 'इस गेम के स्कोर चले जाएँगे। पूरे हुए राउंड्स के स्टैट्स बचे रहेंगे।',
  'game.leaveConfirm': 'गेम छोड़ो',
  'game.notFound': 'कोई गेम नहीं चल रहा',
  'game.goHome': 'होम पर जाओ',
  'game.exit': 'गेम से बाहर',

  'deal.title': 'राज़ फेंटे जा रहे हैं…',
  'deal.subtitle': 'यहाँ कोई झूठ बोलने वाला है।',

  'reveal.passTo': 'फ़ोन इसे दो',
  'reveal.progress': 'प्लेयर {current} / {total}',
  'reveal.lookAway': 'बाकी सब — नज़रें हटाओ 👀',
  'reveal.ready': 'मैं {name} हूँ — दिखाओ',
  'reveal.holdToReveal': 'देखने के लिए दबाकर रखो',
  'reveal.holdHint': 'छुपाने के लिए छोड़ दो',
  'reveal.tapCard': 'देखने के लिए टैप करो',
  'reveal.hideAndPass': 'छुपाओ और फ़ोन आगे दो',
  'reveal.gotIt': 'समझ गया — छुपाओ और आगे दो',
  'reveal.last': 'छुपा दो — सबने देख लिया!',
  'reveal.yourWord': 'तुम्हारा शब्द है',
  'reveal.remember': 'याद रखना! ज़ोर से मत बोलना।',
  'reveal.imposterTitle': 'तुम इम्पोस्टर हो',
  'reveal.imposterBody': 'तुम्हें शब्द नहीं पता।',
  'reveal.imposterTip': 'क्लूज़ ध्यान से सुनो और घुल-मिल जाओ।',
  'reveal.categoryHint': 'कैटेगरी: {category}',
  'reveal.teammates': 'तुम्हारा पार्टनर इन क्राइम: {names}',
  'reveal.undercoverTitle': 'तुम अंडरकवर हो',
  'reveal.undercoverBody': 'बाकी सबके पास अलग शब्द है। घुल-मिल जाओ!',
  'reveal.innocent': '🔍 खबर: {name} इम्पोस्टर टीम में नहीं है।',
  'reveal.suspects': '🕶️ खबर: {a} या {b} में से कोई कुछ छुपा रहा है।',
  'reveal.backgrounded': 'सेफ़्टी के लिए छुपा दिया। जब फ़ोन {name} के हाथ में हो तब टैप करो।',

  'complete.title': 'सबने देख लिया!',
  'complete.body': 'फ़ोन ऐसी जगह रखो जहाँ सब देख सकें।',
  'complete.start': 'क्लू शुरू करो',
  'complete.twists': 'इस राउंड के ट्विस्ट',

  'clue.title': 'क्लू देने का टाइम!',
  'clue.roundN': 'क्लू राउंड {round}',
  'clue.turn': '{name}',
  'clue.giveClue': 'अपना क्लू दो 🗣️',
  'clue.next': 'अगला प्लेयर',
  'clue.done': 'क्लू दे दिया',
  'clue.allDone': 'सारे क्लू आ गए!',
  'clue.allDoneBody': 'एक और राउंड, या अब बहस?',
  'clue.anotherRound': 'एक और क्लू राउंड',
  'clue.startDiscussion': 'बहस शुरू करो',
  'clue.timeUp': 'टाइम खत्म!',
  'clue.order': 'क्लू का क्रम',
  'clue.speedRound': 'स्पीड राउंड: हर क्लू के लिए {count} सेकंड!',

  'peek.button': 'शब्द भूल गए?',
  'peek.title': 'किसे दोबारा देखना है?',
  'peek.body': 'सबको पता चलेगा किसने देखा।',
  'peek.log': '👀 दोबारा देखा: {names}',

  'discussion.title': 'बहस करो',
  'discussion.subtitle': 'कौन संदिग्ध लग रहा है? 🕵️',
  'discussion.pause': 'पॉज़',
  'discussion.resume': 'जारी रखो',
  'discussion.addTime': '+30s',
  'discussion.vote': 'वोटिंग शुरू करो',
  'discussion.timeUp': 'टाइम खत्म! चलो वोट करें।',
  'discussion.paused': 'पॉज़ है',
  'discussion.pausedBackground': 'ऐप बैकग्राउंड में था इसलिए पॉज़ हो गया',
  'discussion.hunt': '{hidden} अभी भी छुपे हैं · {votes} बाकी',
  'discussion.votesLeft_one': '{count} वोट',
  'discussion.votesLeft_other': '{count} वोट',
  'discussion.elapsed': 'बहस चल रही है',

  'vote.title': 'कौन संदिग्ध लग रहा है? 🕵️',
  'vote.revoteTitle': 'फिर से वोट! सिर्फ़ बराबरी वाले प्लेयर्स।',
  'vote.progress': '{done} / {total} वोट',
  'vote.passTo': 'फ़ोन इसे दो',
  'vote.ready': 'मैं {name} हूँ — वोट करने दो',
  'vote.secret': 'जब तक सब वोट न कर दें, वोट सीक्रेट रहेंगे।',
  'vote.chooseFor': '{name}, इम्पोस्टर कौन है?',
  'vote.lockIn': '{name} को वोट लॉक करो',
  'vote.pick': 'किसी को चुनो',
  'vote.locked': 'वोट लॉक हो गया 🔒',
  'vote.lockedBody': 'फ़ोन आगे पास करो।',
  'vote.allIn': 'सबने वोट कर दिया!',
  'vote.allInBody': 'सब इकट्ठा हो जाओ, बड़ा खुलासा होने वाला है…',
  'vote.reveal': 'वोट दिखाओ',
  'vote.selected': 'चुना गया',

  'result.drumroll': 'ग्रुप ने फ़ैसला कर लिया है…',
  'result.votes_one': '{count} वोट',
  'result.votes_other': '{count} वोट',
  'result.tie': 'टाई! 🤝',
  'result.tieBody': '{names} बराबरी पर हैं। फिर से वोट करो।',
  'result.revote': 'फिर से वोट',
  'result.randomTie': '🎲 टाई रैंडम तरीके से टूटा!',
  'result.out': '{name} वोट आउट!',
  'result.revealRole': 'इनका रोल दिखाओ',

  'elim.was': '{name} था…',
  'elim.imposter': 'इम्पोस्टर! 🎭',
  'elim.undercover': 'अंडरकवर! 🥸',
  'elim.civilian': 'बेकसूर 😇',
  'elim.detective': 'डिटेक्टिव 🔍',
  'elim.agent': 'सीक्रेट एजेंट 🕶️',
  'elim.jester': 'जोकर 🃏',
  'elim.jesterBody': 'और यही तो वो चाहता था।',
  'elim.civilianBody': 'उफ़। गलत इंसान।',
  'elim.found': 'तुमने इम्पोस्टर पकड़ लिया!',
  'elim.foundUndercover': 'तुमने अंडरकवर पकड़ लिया!',
  'elim.lastChance': 'पर उसे एक आखिरी मौका मिलेगा…',
  'elim.giveGuess': 'फ़ोन {name} को दो',
  'elim.stillHiding': '{hidden} अभी भी छुपे हैं · {votes} बाकी',
  'elim.moreClues': 'क्लूज़ का एक और राउंड',
  'elim.discuss': 'सीधे बहस पर',
  'elim.seeResults': 'रिज़ल्ट देखो',

  'guess.title': 'आखिरी गेस',
  'guess.passTo': 'फ़ोन इसे दो',
  'guess.ready': 'मैं {name} हूँ — गेस करने दो',
  'guess.question': 'सीक्रेट शब्द क्या था?',
  'guess.questionUndercover': 'बाकी सबका शब्द क्या था?',
  'guess.placeholder': 'अपना गेस टाइप करो…',
  'guess.submit': 'गेस लॉक करो',
  'guess.correct': 'सही! 😱',
  'guess.wrong': 'गलत! 🎉',
  'guess.theWordWas': 'शब्द था',
  'guess.youGuessed': '{name} ने गेस किया “{guess}”',
  'guess.accept': 'काफ़ी करीब — मान लो',
  'guess.acceptedByGroup': 'ग्रुप ने मान लिया',

  'win.civilians': 'सिविलियन्स जीते!',
  'win.imposters': 'इम्पोस्टर्स जीते!',
  'win.undercovers': 'अंडरकवर जीता!',
  'win.jester': 'जोकर जीता!',
  'win.reason.allCaught': 'हर इम्पोस्टर पकड़ा गया और किसी ने शब्द गेस नहीं किया।',
  'win.reason.imposterSurvived': 'एक इम्पोस्टर वोट से बच निकला।',
  'win.reason.imposterGuessed': 'पकड़ा तो गया… पर शब्द गेस कर लिया!',
  'win.reason.jesterVotedOut': 'तुमने जोकर को वोट आउट कर दिया। वही पुरानी गलती।',
  'win.reason.allCaught.undercover': 'हर अंडरकवर प्लेयर पकड़ा गया और किसी ने शब्द गेस नहीं किया।',
  'win.reason.imposterSurvived.undercover': 'एक अंडरकवर प्लेयर वोट से बच निकला।',
  'win.reason.imposterGuessed.undercover': 'पकड़ा तो गया… पर सबका शब्द गेस कर लिया!',
  'win.secretWord': 'सीक्रेट शब्द',
  'win.undercoverWord': 'अंडरकवर शब्द',
  'win.roles': 'कौन क्या था',
  'win.scoreboard': 'स्कोरबोर्ड',
  'win.eliminated': 'आउट',

  'role.civilian': 'सिविलियन',
  'role.imposter': 'इम्पोस्टर',
  'role.undercover': 'अंडरकवर',
  'role.detective': 'डिटेक्टिव',
  'role.jester': 'जोकर',
  'role.agent': 'सीक्रेट एजेंट',
  'role.civilian.card': 'सिविलियन',
  'role.detective.card': 'डिटेक्टिव',
  'role.agent.card': 'सीक्रेट एजेंट',
  'role.jester.card': 'जोकर',
  'role.detective.tip': 'तुम्हारे पास खबर है। सोच-समझकर इस्तेमाल करो — अपनी पहचान मत खोलना।',
  'role.agent.tip': 'तुम सिविलियन्स की साइड हो, और तुम्हारे पास एक सीक्रेट सुराग है।',
  'role.jester.tip': 'अगर ग्रुप तुम्हें वोट आउट करे तो तुम जीतोगे। संदिग्ध बनकर दिखाओ!',
  'role.detective.desc': 'एक सिविलियन जिसे पता होता है कि एक प्लेयर पक्का बेकसूर है।',
  'role.jester.desc': 'शब्द पता है, पर जीतता तभी है जब वोट आउट हो। पूरा केऑस।',

  'scoreboard.title': 'स्कोरबोर्ड',
  'scoreboard.afterRound': 'राउंड {round} के बाद',
  'scoreboard.nextRound': 'अगला राउंड',
  'scoreboard.endGame': 'गेम खत्म करो',
  'scoreboard.scoringOff': 'स्कोरिंग ऑफ़ है — बस शेखी बघारने के लिए।',

  'final.title': 'गेम ओवर!',
  'final.winner': '{name} बना बादशाह 👑',
  'final.tie': 'टॉप पर टाई है!',
  'final.rounds_one': '{count} राउंड खेला',
  'final.rounds_other': '{count} राउंड खेले',
  'final.playAgain': 'फिर से खेलो',
  'final.home': 'होम',

  'twist.shortClues': 'क्लू 3 या उससे कम शब्दों का होना चाहिए।',
  'twist.firstOneWord': 'पहला क्लू सिर्फ़ एक शब्द का होना चाहिए।',
  'twist.noRepeat': 'जो आइडिया कोई बोल चुका है, उसे दोहराना मना है।',
  'twist.noPhysical': 'दिखावट बताना मना है — न रंग, न आकार, न साइज़।',
  'twist.lastRestriction': '{name} आखिर में बोलेगा और सिर्फ़ आवाज़ या इशारा कर सकता है!',
  'twist.speedRound': 'स्पीड राउंड! हर क्लू के लिए {count} सेकंड।',
  'twist.randomOrder': 'क्लू का क्रम पूरा उलट-पुलट है।',
  'twist.secretAgent': 'तुम्हारे बीच एक सीक्रेट एजेंट है…',
  'twist.imposterCategory': 'इस बार इम्पोस्टर को कैटेगरी पता है।',
  'twist.twoWords': 'दो अलग-अलग शब्द चल रहे हैं। किसी पर भरोसा मत करो।',

  'rules.title': 'कैसे खेलें',
  'rules.basics.title': 'बेसिक्स',
  'rules.basics.body':
    'सबको चुपके से एक ही शब्द मिलता है — सिवाय इम्पोस्टर के, जिसे कुछ नहीं मिलता। बारी-बारी से शब्द के बारे में एक क्लू दो। फिर बहस करो और जिस पर नाटक करने का शक हो, उसे वोट आउट करो।',
  'rules.example.title': 'उदाहरण',
  'rules.example.body':
    'शब्द है पिज़्ज़ा। राघव कहता है “चीज़ी”। प्रिया कहती है “स्लाइस”। अरुण (इम्पोस्टर, जिसे सिर्फ़ कैटेगरी खाना पता है) कहता है “डिलीवरी”… सही लगता है! फिर नेहा कहती है “इटैलियन” और अरुण को पसीना आने लगता है।',
  'rules.classic.title': '🎭 क्लासिक',
  'rules.classic.body': 'इम्पोस्टर को सिर्फ़ कैटेगरी दिखती है (जैसे “खाना”) और उसे ब्लफ़ करना है।',
  'rules.blind.title': '🙈 ब्लाइंड',
  'rules.blind.body': 'इम्पोस्टर को कुछ भी नहीं मिलता — कैटेगरी भी नहीं। झूठों के लिए हार्ड मोड।',
  'rules.undercover.title': '🥸 अंडरकवर',
  'rules.undercover.body':
    'बिना शब्द के बजाय, अलग वाले को मिलता-जुलता शब्द मिलता है (पिज़्ज़ा vs बर्गर)। डिफ़ॉल्ट रूप से उसे पता भी नहीं होता कि वो अलग है! उसके क्लू लगभग सही लगेंगे…',
  'rules.multi.title': '👥 कई इम्पोस्टर्स',
  'rules.multi.body':
    '5+ प्लेयर्स के साथ 2 इम्पोस्टर्स रख सकते हो, और 7+ के साथ 3। सिविलियन्स को हर इम्पोस्टर के लिए एक वोट मिलता है और सबको बाहर करना होता है। एक भी बच गया तो इम्पोस्टर्स जीत जाते हैं।',
  'rules.chaos.title': '🌀 केऑस',
  'rules.chaos.body':
    'हर राउंड में रैंडम ट्विस्ट आते हैं: स्पीड राउंड, एक शब्द वाले क्लू, एक सीक्रेट एजेंट जिसे दो संदिग्धों में से एक पता होता है, एक दूसरा सीक्रेट शब्द, और भी बहुत कुछ।',
  'rules.voting.title': '🗳️ वोटिंग',
  'rules.voting.body':
    'फ़ोन घुमाओ — सब चुपके से वोट करते हैं, और जब तक सारे वोट न आ जाएँ, कोई रिज़ल्ट नहीं देखता। खुद को वोट नहीं कर सकते। सबसे ज़्यादा वोट वाला प्लेयर आउट होता है और उसका रोल खुलता है।',
  'rules.tie.title': '🤝 टाई',
  'rules.tie.body':
    'अगर टॉप पर टाई हो, तो सिर्फ़ बराबरी वाले प्लेयर्स के बीच फिर से वोट होता है (या रैंडम चुनाव, अगर तुमने वो चुना है)। फिर से टाई हुआ तो फ़ोन रैंडम चुनता है।',
  'rules.guess.title': '🎯 आखिरी गेस',
  'rules.guess.body':
    'पकड़े गए इम्पोस्टर को एक आखिरी मौका मिलता है: सीक्रेट शब्द गेस करो। सही? इम्पोस्टर्स जीते। गलत? सिविलियन्स जीते (अगर हर इम्पोस्टर पकड़ा गया हो)।',
  'rules.roles.title': '🃏 स्पेशल रोल्स (ऑप्शनल)',
  'rules.roles.body':
    'डिटेक्टिव: एक सिविलियन जिसे पता होता है कि एक प्लेयर पक्का बेकसूर है। जोकर: शब्द जानता है पर जीतता सिर्फ़ वोट आउट होकर — ऐसा हुआ तो राउंड खत्म और इम्पोस्टर्स भी जीत जाते हैं।',
  'rules.scoring.title': '🏆 स्कोरिंग',
  'rules.scoring.body':
    'सिविलियन्स: इम्पोस्टर पर हर वोट के लिए +2, सिविलियन्स जीतें तो हर एक को +1। इम्पोस्टर्स: बचने पर +3, शब्द गेस करने पर +5। जोकर: वोट आउट होने पर +5। पॉइंट्स गेम सेटिंग्स में बदल सकते हो।',
  'rules.tips.title': '💡 टिप्स',
  'rules.tips.body':
    'सिविलियन्स: इतना साफ़ बोलो कि लगे तुम्हें पता है, पर इतना नहीं कि पोल खुल जाए। इम्पोस्टर्स: पहले सुनो, फिर कुछ सेफ़ बोलो। सब लोग: चुप रहना भी शक पैदा करता है।',

  'stats.title': 'स्टैट्स',
  'stats.empty': 'अभी तक कोई गेम नहीं। एक राउंड खेलो, स्टैट्स यहाँ दिखेंगे — सब असली, कुछ भी बनावटी नहीं।',
  'stats.overview': 'इस फ़ोन के सारे गेम्स',
  'stats.rounds': 'खेले गए राउंड',
  'stats.civilianWins': 'सिविलियन की जीत',
  'stats.imposterWins': 'इम्पोस्टर की जीत',
  'stats.jesterWins': 'जोकर की जीत',
  'stats.players': 'प्लेयर्स',
  'stats.gamesPlayed': 'खेले गए गेम्स',
  'stats.wins': 'जीत',
  'stats.losses': 'हार',
  'stats.winRate': 'जीत का रेट',
  'stats.imposterGames': 'इम्पोस्टर वाले गेम्स',
  'stats.imposterWinsP': 'इम्पोस्टर बनकर जीत',
  'stats.civilianGames': 'सिविलियन वाले गेम्स',
  'stats.timesCaught': 'कितनी बार पकड़े गए',
  'stats.successfulGuesses': 'सही गेस किए शब्द',
  'stats.bestStreak': 'बेस्ट स्ट्रीक',
  'stats.currentStreak': 'मौजूदा स्ट्रीक',
  'stats.points': 'कुल पॉइंट्स',
  'stats.summaryLine': '{wins} · {rate}% जीत का रेट',
  'stats.winCount_one': '{count} जीत',
  'stats.winCount_other': '{count} जीत',

  'settings.title': 'सेटिंग्स',
  'settings.appearance': 'लुक',
  'settings.theme': 'थीम',
  'settings.theme.dark': 'डार्क',
  'settings.theme.light': 'लाइट',
  'settings.theme.system': 'सिस्टम',
  'settings.motion': 'एनिमेशन',
  'settings.motion.system': 'सिस्टम',
  'settings.motion.full': 'पूरा',
  'settings.motion.reduced': 'कम',
  'settings.language': 'भाषा',
  'settings.language.system': 'सिस्टम',
  'settings.sound': 'साउंड और फ़ील',
  'settings.soundEffects': 'साउंड इफ़ेक्ट्स',
  'settings.music': 'म्यूज़िक',
  'settings.haptics': 'वाइब्रेशन',
  'settings.gameplay': 'गेमप्ले',
  'settings.revealStyle': 'सीक्रेट कैसे दिखे',
  'settings.reveal.tap': 'टैप',
  'settings.reveal.hold': 'होल्ड',
  'settings.revealHint': 'होल्ड = सीक्रेट तभी दिखेगा जब तक उंगली दबी है।',
  'settings.allowPeek': '“शब्द भूल गए?” की इजाज़त दो',
  'settings.keepAwake': 'गेम के दौरान स्क्रीन ऑन रखो',
  'settings.data': 'तुम्हारा डेटा',
  'settings.exportData': 'प्लेयर्स, कैटेगरी और सेटिंग्स एक्सपोर्ट करो',
  'settings.importData': 'टेक्स्ट से इम्पोर्ट करो',
  'settings.resetStats': 'स्टैट्स रीसेट करो',
  'settings.resetStatsTitle': 'पक्का?',
  'settings.resetStatsBody': 'सारे स्टैट्स मिट जाएँगे। ये वापस नहीं होगा।',
  'settings.resetStatsDone': 'स्टैट्स रीसेट हो गए।',
  'settings.replayTutorial': 'इंट्रो फिर से देखो',
  'settings.about': 'ऐप के बारे में',
  'settings.privacy': 'न अकाउंट, न ऐड्स, न ट्रैकिंग। सब कुछ इसी फ़ोन में रहता है।',
  'settings.version': 'वर्ज़न {version}',
  'settings.importDone': 'इम्पोर्ट हो गया! {categories} कैटेगरी, {players} प्लेयर्स।',
  'settings.exportShare': 'Imposter Party बैकअप',

  'category.tamil_nadu': 'तमिलनाडु',
  'category.tamil_movies': 'तमिल फ़िल्में',
  'category.tamil_celebrities': 'तमिल सेलिब्रिटीज़',
  'category.telugu_cinema': 'तेलुगु सिनेमा',
  'category.malayalam_cinema': 'मलयालम सिनेमा',
  'category.poolSummary': 'रैंडम और मिक्स {total} में से {on} टॉपिक इस्तेमाल करते हैं',
  'category.poolEdit': 'टॉपिक चुनो',
  'group.everyday': 'रोज़ की चीज़ें',
  'group.india': 'भारत और तमिलनाडु',
  'group.cinema': 'फ़िल्में और सितारे',
  'group.pop': 'खेल, गेम्स और पॉप कल्चर',
  'categories.poolTitle': 'रैंडम और मिक्स के टॉपिक',
  'categories.poolHint':
    'जो टॉपिक आपके ग्रुप को नहीं पता, उन्हें ऑफ़ करो। रैंडम और मिक्स उन्हें छोड़ देंगे — फिर भी आप कोई भी कैटेगरी सीधे चुन सकते हो।',
  'categories.poolCount': '{total} में से {on} टॉपिक ऑन',
  'categories.preset.all': 'सभी',
  'categories.preset.everyday': 'रोज़ की चीज़ें',
  'categories.preset.tamil': 'तमिल स्पेशल',
  'categories.preset.pop': 'फ़िल्में और पॉप',
  'categories.presets': 'झटपट चुनो',
  'categories.customInRandom': 'मेरी कैटेगरी रैंडम और मिक्स में भी',
  'categories.toggleHint': '{words} · रैंडम और मिक्स में',
  'config.error.noCategories': 'रैंडम और मिक्स के लिए कम से कम एक टॉपिक ऑन होना चाहिए',
  'simple.title': 'सबने अपना शब्द देख लिया!',
  'simple.starts': '{name} शुरू करेगा',
  'simple.clockwise': 'फिर घड़ी की दिशा में',
  'simple.anticlockwise': 'फिर घड़ी की उल्टी दिशा में',
  'simple.orderLabel': 'बोलने का क्रम',
  'simple.phoneDown': 'फ़ोन नीचे रखो 📵 क्लू, बहस और वोटिंग सब ज़ोर से बोलकर करो।',
  'simple.holdReveal': 'जवाब देखने के लिए दबाकर रखो',
  'simple.holdHint': 'सिर्फ़ तब जब सबने वोट कर दिया हो!',
  'simple.holding': 'दबाए रखो…',
  'answer.title': 'जवाब',
  'answer.imposter_one': 'इम्पोस्टर था',
  'answer.imposter_other': 'इम्पोस्टर्स थे',
  'answer.undercover_one': 'अंडरकवर था',
  'answer.undercover_other': 'अंडरकवर थे',
  'answer.compare': 'क्या आपके ग्रुप ने सही पकड़ा? 🤔',
  'answer.nextRound': 'अगला राउंड',
  'settings.playStyle': 'कैसे खेलते हो',
  'settings.playStyle.simple': 'सिर्फ़ शब्द',
  'settings.playStyle.full': 'पूरा गेम',
  'settings.playStyle.simpleHint':
    'फ़ोन सीक्रेट शब्द बाँटता है, बताता है कौन शुरू करेगा और किस दिशा में जाना है, फिर आख़िर में जवाब दिखाता है। क्लू, बहस और वोटिंग ज़ोर से बोलकर होती है।',
  'settings.playStyle.fullHint': 'क्लू, टाइमर, सीक्रेट वोटिंग, इम्पोस्टर का आख़िरी गेस और स्कोर — सब फ़ोन पर।',
  'config.playStyleNote': 'खेल: {style} · सेटिंग्स में बदलो',
  'rules.styles.title': '📱 खेलने के दो तरीके',
  'rules.styles.body':
    'सिर्फ़ शब्द (डिफ़ॉल्ट): फ़ोन घुमाओ ताकि सब अपना शब्द देख लें, फिर फ़ोन बताएगा कौन शुरू करेगा और किस दिशा में। फ़ोन नीचे रखो, क्लू दो, बहस करो और ज़ोर से वोट करो — फिर बटन दबाकर देखो असली इम्पोस्टर कौन था। पूरा गेम (सेटिंग्स → कैसे खेलते हो): क्लू, टाइमर, सीक्रेट वोटिंग, आख़िरी गेस और स्कोर सब फ़ोन पर।',
  'players.empty': 'कम से कम 3 प्लेयर्स जोड़ो, घड़ी की दिशा में बैठने के क्रम में — इसी क्रम में फ़ोन पास करना है।',
};
